### ISSUE TITLE
TypeError: list indices must be integers or slices, not tuple

### ISSUE THREAD

**Issue by Varat7v2** [abewley/sort#108]
I am trying to use SORT in my project, but I am getting following error. I am trying to track the error but not able to find why its occurring. 

```
File "sort.py", line 242, in update
    trk = KalmanBoxTracker(dets[i,:])
TypeError: list indices must be integers or slices, not tuple
```

**Comment by Veronica1997** [comment]
I meet the same problem with you ,have you solved it? Thanks very much!

**Comment by pilarpe4** [comment]
Same here!

**Comment by abewley** [comment]
Can you please provide more information on how to reproduce this error? Are you passing dets as a 2D numpy array following what is described in the update() doc string? If not you can easily create a numpy array as pilarpe4@ described.

**Comment by manish33scss** [comment]
i changed the whole sort file, copy pasted from original doc, attaching file for that i am using, 
[sort_copied.txt](https://github.com/abewley/sort/files/6078113/sort_copied.txt)

 for x1, y1, x2, y2, obj_id, cls_pred in tracked_objects: (so this sort will return bbox coordinates, id and cls)

**Comment by sampreets3** [comment]
> i changed the whole sort file, copy pasted from original doc, attaching file for that i am using,
> [sort_copied.txt](https://github.com/abewley/sort/files/6078113/sort_copied.txt)
> 
> for x1, y1, x2, y2, obj_id, cls_pred in tracked_objects: (so this sort will return bbox coordinates, id and cls)

How do I go about using this new file? What I have done is I have copied and pasted the txt file into the sort.py file, and re-ran the application. This still gives me the error :
```
  File "<root-repo>\sort.py", line 216, in update
    trk = KalmanBoxTracker(dets[i,:])
TypeError: list indices must be integers or slices, not tuple
```

**Comment by manish33scss** [comment]
> > i changed the whole sort file, copy pasted from original doc, attaching file for that i am using,
> > [sort_copied.txt](https://github.com/abewley/sort/files/6078113/sort_copied.txt)
> > for x1, y1, x2, y2, obj_id, cls_pred in tracked_objects: (so this sort will return bbox coordinates, id and cls)
> 
> How do I go about using this new file? What I have done is I have copied and pasted the txt file into the sort.py file, and re-ran the application. This still gives me the error :
> 
> ```
>   File "<root-repo>\sort.py", line 216, in update
>     trk = KalmanBoxTracker(dets[i,:])
> TypeError: list indices must be integers or slices, not tuple
> ```

I tried this, again, its working, as far as i can remember i got this error while updating something in those files. just find out what is the type of detections, 
i am pasting my piece of code that is invoking tracker.  and type of detections and tracked_objects

**        detections=detections.type(torch.DoubleTensor)
        
        tracked_objects = mot_tracker.update(detections)
        detectionstest.append(detections)
        box = detections[0:4]**

type(detections)
Out[2]: torch.Tensor

type(tracked_objects)
Out[3]: numpy.ndarray

and can you try this sort code, on a different pc ? i think you  might have to reinstall some stuff. ( just a wild guess)

**Comment by KC-Zhang** [comment]
the input to update() must be an np array rather than list of lists
