### ISSUE TITLE
score

### ISSUE THREAD

**Issue by stevekd** [abewley/sort#12]
(x, y, w, h, score) score what is the meaning of how to calculate the score d [4]

**Comment by Ravisik** [comment]
Score is the probability given in output by the neural network.
i.e: score = 0 no detection, score = 0.5 not sure if it is a good detection score = 1.0 totally sure that there is a detection.

If you use py-faster-rcnn you just have to get score like this: 
scores, boxes = im_detect(net, frame)

**Comment by abewley** [comment]
Thanks Ravisik is correct, the score is just a confidence measure to compare between detections.
 
I'd like to also add that the SORT tracker itself doesn't directly make use of the score so unless you need it for your downstream evaluation you could just set it to 1.0 for all detections (assuming your detector is reasonable and doesn't provide its own score).

**Comment by abewley** [comment]
Closing issue for now. If you need further clarification you can reopen it.
