### ISSUE TITLE
Sort update result box value different than detection

### ISSUE THREAD

**Issue by KyloEntro** [abewley/sort#120]
Hi,

I analyse the result returned by sort.update(). 
The bounding box of an object is little different than detection value. 

For example, if the object bounding box is (1, 3, 4, 5) in n_th frame, sort.update() return (1, 2.9, 3.6, 5.1, id)

Is it normal ?

**Comment by abewley** [comment]
Yes, that is normal as the returned boxes are the optimal estimates from a Kalman filter process which is fusing information from multiple timesteps.

**Comment by KyloEntro** [comment]
Thanks 👍
