### ISSUE TITLE
Video link missing

### ISSUE THREAD

**Issue by neilyoung** [abewley/sort#124]
https://motchallenge.net/movies/ETH-Linthescher-SORT.mp4

doesn't resolve

**Comment by abewley** [comment]
Try the following for now but I'll update this soon.
https://motchallenge.net/movies/d80cceb92629e8236c60129417830bd2fdec8025-MOT17-06-FRCNN.webm

Thanks for reminding me (please leave ticket open).

**Comment by neilyoung** [comment]
Cool. Thanks for the quick answer. This looks great. Do you have some info, on what device this was computed?

**Comment by abewley** [comment]
The tracking results were computed on a Late 2013 model MacBook Pro laptop. The video is generated from the results uploaded to the MOT17 benchmark. The specific link provided matches the save detector from the original paper.

I've updated the video link in the README to a copy of the video so closing this ticket.
