### ISSUE TITLE
convert_x_to_bbox function output

### ISSUE THREAD

**Issue by miketry0313** [abewley/sort#13]
Thanks for making the code public.

1. It seems that 'convert_x_to_bbox' output points at the **bottom left and the top right**.

    Is this a typo in the function comment?

2. Also would you please advise that why a **minus** iou_matrix passed to linear assignment module?

**Comment by abewley** [comment]
In the code I use the convention that y increases in the downward image direction. So the [x1, y1, x2, y2] could also read [left,top,right,bottom], that's what I meant when referring to the box's top left corner point (x1,y1) and the bottom right corner point (x2, y2).  There was a typo in the comment where I had [x1, y1, x2, x2] but that should now be fixed. Sorry for any confusion.

The linear assignment module tries to minimise the total assignment cost. In our case we pass -iou_matrix as we want to maximise the total IOU between track predictions and the frame detection.

**Comment by miketry0313** [comment]
Thanks a lot!
