### ISSUE TITLE
SORT Paper Scores are inconsistent with Metric Evaluation suits

### ISSUE THREAD

**Issue by capricornfati** [abewley/sort#132]
Hello,

I have been experiencing difficulties to reproduce MOTChallenge scores of SORT tracker for MOT15 dataset. I used det.txt provided in git repo of the paper (frcnn detections). I double checked the evauation scores by calculating on https://github.com/JonathonLuiten/TrackEval and https://github.com/cheind/py-motmetrics . I have attached my results in png for py-motmetrics and .csv and .txt formats for TrackEval. Scores such as IDsw, MOTA, Frag scores are different between the paper and the evaluation results. I am trying the understand the reason between these inconsistencies. Are the detections used for getting the results on the paper different than provided in the repo? Thank you.
 
![Screenshot from 2021-05-05 20-06-53](https://user-images.githubusercontent.com/26479849/117186053-23848180-ade3-11eb-985a-0e361d9a256a.png)

[pedestrian_detailed.csv](https://github.com/abewley/sort/files/6429164/pedestrian_detailed.csv)
[pedestrian_summary.txt](https://github.com/abewley/sort/files/6429167/pedestrian_summary.txt)

Fatih.

**Comment by abewley** [comment]
These look like training sequences while the paper reports values for the
test sequences.

**Comment by capricornfati** [comment]
Omg what a mistake! I should have been more careful while reading the paper. Thank you Sir!.

Sincerely,
Fatih
