### ISSUE TITLE
Wrong format in comment

### ISSUE THREAD

**Issue by Rizhiy** [abewley/sort#15]
In update method of the tracker on [this line](https://github.com/abewley/sort/blob/f088389fabd9fdfd0d5f80a63d52649338d02807/sort.py#L188), it says in the comment that input format is supposed to be `x,y,w,h,score` while in reality, it expects `x1,y1,x2,y2,score` as can be further seen in [usage example](https://github.com/abewley/sort/blob/f088389fabd9fdfd0d5f80a63d52649338d02807/sort.py#L266).

Also might be a good idea to explicitly state return format.

**Comment by abewley** [comment]
You're right, I've updated the doctoring so will now close this issue.
