### ISSUE TITLE
How can i get the det format description?

### ISSUE THREAD

**Issue by beebrain** [abewley/sort#150]
I can't find the det format description. Please, anyone, tell me where can I get the information of det format?

I have less information from det file. I thought that It's come from a detecter algorithm such as Yolo Fast R-CNN.
However, I would like to know the number -1 after the confidence score. What does it mean?
For example
1,-1,1691.97,381.048,152.23,352.617,0.995616,-1,-1,-1
1,-1,1233.55,467.507,133.65,218.985,0.980069,-1,-1,-1
1,-1,108.484,461.531,97.759,297.453,0.942438,-1,-1,-1
1,-1,256.996,420.694,101.497,296.434,0.938051,-1,-1,-1
1,-1,19.5685,469.707,87.4595,343.434,0.872169,-1,-1,-1
1,-1,1869.09,376.414,49.91,222.562,0.754415,-1,-1,-1
1,-1,1252.28,509.199,59.49,133.608,0.65418,-1,-1,-1
1,-1,0,265.374,109.767,381.325,0.629887,-1,-1,-1

A first column is a frame number. The second I have no idea, and the other -1 in other columns.
The 3rd to 7th columns are x,y,h,w, and confidence score respectively. 
Anyone, please tell me, the -1 values Where does come from?

**Comment by ouyang11111** [comment]
i have same question ,we could trace where the number is used

**Comment by cappittall** [comment]
Hi @beebrain & @ouyang11111 

I think the relevant information you can find at the [link](https://motchallenge.net/instructions/)

**Comment by abhiksark** [comment]
This can be part of Readme as well.

**Comment by varungupta31** [comment]
The format is defined in the [MOT16: A Benchmark for Multi-Object Tracking](https://arxiv.org/pdf/1603.00831.pdf) paper.
And as per the paper,

>The first number indicates in which frame the object appears, while the second number identifies that object as belonging to a  trajectory by assigning a unique ID (set to −1 in a detection file, as no ID is assigned yet). Each object can be assigned to only one trajectory. The next four numbers indicate the position of the bounding box of the pedestrian in 2D image coordinates. The position is indicated by the top-left corner as well as width and height of the bounding box. This is followed by a single number, which in case of detections denotes their confidence score. The last two numbers for detection files are ignored (set to -1).

Hope this helps.

**Comment by beebrain** [comment]
Thank you for all your help. I got the information. 
I have closed this issue.
