### ISSUE TITLE
Linear_assignment... What is it...

### ISSUE THREAD

**Issue by ehdrndd** [abewley/sort#152]
In 
```python
def linear_assignment(cost_matrix):
  try:
    import lap
    _, x, y = lap.lapjv(cost_matrix, extend_cost=True)
    return np.array([[y[i],i] for i in x if i >= 0]) #
  except ImportError:
    from scipy.optimize import linear_sum_assignment
    x, y = linear_sum_assignment(cost_matrix)
    return np.array(list(zip(x, y)))
```

![image](https://user-images.githubusercontent.com/81725328/147728068-3975c795-19f6-463b-9d1c-129f449dc365.png)

above image is output of 
```python
import lap
_, x, y = lap.labjv(cost_matrix, extend_cost=True)
```
First, i understood variables as minimum_cost index of rows, cols. But, x[5]=-1, x[6]=4, y[4]=7. ?? I can't understand those values...

Second, there are differences `lap.labjv` with `linear_sum_assignment`
```python
from scipy.optimize import linear_sum_assignment
x2, y2 = linear_sum_assignment(cost_matrix)
```
![image](https://user-images.githubusercontent.com/81725328/147729044-14c0bc97-9496-4856-a242-bb90e9c6708d.png)

![image](https://user-images.githubusercontent.com/81725328/147728583-ebe091e3-7726-49a2-b9fd-1ac51ab7a8e1.png)

Can you help me?

**Comment by ehdrndd** [comment]
I understood linear_sum_assignment!!

https://brc2.com/the-algorithm-workshop/

and my second question is trivial question. because rows 6,7 are all zeros..

**Comment by microchila** [comment]
I would like to ask if the Hungarian algorithm can accept negative cost matrices？and what is the reason for sort to take a negative iou distance as a cost matrix?
