### ISSUE TITLE
Smmothing detections using tracking

### ISSUE THREAD

**Issue by abhiagwl4262** [abewley/sort#17]
I want to smooth out my detection using tracking. E.g if some object is detected by my detection algorithm in frame 5 and not detected in next 4 frame, in that case .....i want to track that object for at least 4 frames(if it is not detected in 4 frames continuously, I won't track it.). I hope, I'm clear with that.

Can you guide me with the required changes?

**Comment by abewley** [comment]
You should be able to achieve this through the min_hits and max_age parameters of the[ tracker initialiser.](https://github.com/abewley/sort/blob/master/sort.py#L176)

**Comment by abhiagwl4262** [comment]
Thanks. I was able to resolve this issue.
I changed the following line to https://github.com/abewley/sort/blob/master/sort.py#L222 
        if((trk.time_since_update < **self.max_age+1**) and (trk.hit_streak >= self.min_hits or self.frame_count <= self.min_hits)):

and set min_hits=0 and max_age=4

**Comment by kkyiss** [comment]
Hey @abhiagwl4262 
Could you tell me why you are adding self.max_age to this line?
thanks!

**Comment by abhiagwl4262** [comment]
@kkyiss max_age ensures the case of occlusion. So if a track is lost then we don't keep that track aside, instead we try to track that object until max_age frames(even after disappearance).

I hope, I am clear.

**Comment by sherlockchou86** [comment]
@abhiagwl4262 has explained why the max_age variable exists in SORT code, but do not answer why he added self.max_age to this line.

by default, the SORT tracker would only return the targets which have been updated(matched by detections or new detections) in current frame. but sometimes some targets would not be detected for few frames by detector, the missed targets would not be returned by SORT in this manner.

if we want SORT to return the missed targets even if they are missed by few frames, we need change the code 
`if((trk.time_since_update < 1) and (trk.hit_streak >= self.min_hits or self.frame_count <= self.min_hits)):`
to
`if((trk.time_since_update <= self.max_age) and (trk.hit_streak >= self.min_hits or self.frame_count <= self.min_hits)):`
and `set min_hits == 0`

this means the SORT would return any targets in SORT's cache(predicting location for those not updated), as long as they have not been missed for frames of self.max_age. it is very useful for some situations such as the detector is not good enough and it always misses some small targets in the detecting step before tracking.

there is a drawback that the SORT will return targets which have already disappeared indeed, for example the targets arrive at the edge of the picture and cannot be detected by detector. we should ignore the targets of which location points are out of range, and also the self.max_age should not be set too large or the number of missed targets are too large to maintain in SORT's cache.
