### ISSUE TITLE
Run with MOT test files

### ISSUE THREAD

**Issue by fengyuxi55** [abewley/sort#2]
Hi, Alex, thanks for your great job
I'm trying to run this work with MOT test files:
I modify sort.py to read the dets file in '$MOT2015/test/PETS09-S2L2/det/det.txt'
and set '$MOT2015/test/PETS09-S2L2/img1/xxxxxx.jpg' as input frame
But it cannot work correctly, No tracking bbox on my display window
Anything I missed ?

**Comment by abewley** [comment]
I've changed the bounding box format from [x1,y1,x2,y2] to [x1,y1,w,h] to match the MOT format.
This should allow you to run it with the MOT provided detections. However, please keep in mind that best performance is achieved by using FasterRCNN detections as discussed in the arxiv paper.
