### ISSUE TITLE
2DMOT2015  dataset label question

### ISSUE THREAD

**Issue by Phoebe-star** [abewley/sort#20]
data/PETS09-S2L1/det.txt
the line 1  is  1,-1,649.441,231.502,44.417,86.13,0.995474,-1,-1,-1
what does it mean  and  what  the det.txt  can do   ?  ( including  every  -1  and   0.995474

**Comment by Phoebe-star** [comment]
I got it   https://motchallenge.net/instructions/

**Comment by Phoebe-star** [comment]
how to extend it using CNN

**Comment by Phoebe-star** [comment]
how  is  the conf  value  produce ?

**Comment by abewley** [comment]
The confidence value (0.995474 in your example) was computed as part of the FasterRCNN detector. This is the value after the softmax for the output corresponding to probability the box is a pedestrian/person as expressed by the detection network. 

Regarding to your other question about "how to extend it using CNN", I was going to point you to the [Deep SORT version](https://github.com/nwojke/deep_sort) of this work, but I see you already posted on that repo. The possibilities are endless, so my only advice is to read and understand the papers along with your CNN framework of choice and you will find a way.

**Comment by Phoebe-star** [comment]
I got it ,thanks   thanks
