### ISSUE TITLE
print class value in python?

### ISSUE THREAD

**Issue by Phoebe-star** [abewley/sort#21]
Hi  do you know how to show the class value in python ?
I want to debug it

**Comment by abewley** [comment]
You are welcome to implement a __str__(self) method for the class and make a pull request.

**Comment by 3073** [comment]
@abewley
Could you have some time to add a SSD detector for this SORT tracker?

**Comment by abewley** [comment]
Sorry, I don't have the time but you can find most pre-generated detections via the [DeepSORT repo](https://github.com/nwojke/deep_sort)
