### ISSUE TITLE
Tracking with frame skips

### ISSUE THREAD

**Issue by TheMikeyR** [abewley/sort#22]
Hello, I have some issues regarding tracking with skip in detections. I'm trying to get frameskip to work with this tracker. 
How I expect it to work:

1. Initialise tracking by feeding it with x detections with no frame skip (e.g. 5 frames).
2. Now only use detection every q frame (q frame could be 3 frames)
3. For every frame feed tracker detection list, if no detection is run feed an empty list. According to requirement for Sort function. 

According to Sort(object) comment: `Requires: this method must be called once for each frame even with empty detections.`  

How it works:  
Tracks fine in the initialization, but when I feed the tracker an empty detection it gives an empty tracking result out. Furthermore on the upcoming third frame (after 2 frame skips) it makes a new detection and input this list into the tracker but the tracker output is still empty. 

Do you know what I'm doing wrong in my implementation?

My implementation (edited for easier readability):
It's running in a while loop where each loop counts ix up which grabs the next frame of the video. 
```
if skip_count == detection_frame_skip or ix < 5: # detection_frame_skip = 2
            # Make a detection on the image
            r = detect_np(net, meta, img) #
            skip_count = 0
        else:
            r = []
            skip_count += 1
        detections = []
        if r:
            for detection in r:
                # Some data-handling
                probability = detection[1]
                x, y, w, h = detection[2][0], detection[2][1], detection[2][2], detection[2][3]
                x_min, y_min, x_max, y_max = convertBack(float(x), float(y), float(w), float(h))
                # Save detection in sort format
                detections.append([x_min, y_min, x_max, y_max, probability])
        # Convert detection from list to numpy array for sort
        detections = np.array(detections)
        print(detections)
        tracker_results = tracker.update(detections)
        print(tracker_results)
```

Output of the terminal (edited, removed many detections and only kept one for simplicity)
```
$ python main.py
Img load: 0.06 seconds
Detect: 0.04 seconds
[[  3.75000000e+02   5.99000000e+02   4.74000000e+02   6.67000000e+02
    9.92387056e-01]
[[  1.76200000e+03   2.52000000e+02   1.89700000e+03   3.56000000e+02
    2.30000000e+01]
Img load: 0.06 seconds
Detect: 0.04 seconds
[[  3.76000000e+02   5.99000000e+02   4.74000000e+02   6.67000000e+02
    9.92466390e-01]
[[  1.74125536e+03   2.58809752e+02   1.88174823e+03   3.66188550e+02
    2.30000000e+01]

Img load: 0.06 seconds
Detect: 0.04 seconds
[[  3.76000000e+02   5.98000000e+02   4.74000000e+02   6.67000000e+02
    9.92073357e-01]
[[  1.72014292e+03   2.55391698e+02   1.86403637e+03   3.64960492e+02
    2.30000000e+01]

Img load: 0.06 seconds
Detect: 0.04 seconds
[[  3.76000000e+02   5.97000000e+02   4.74000000e+02   6.66000000e+02
    9.92073357e-01]
[[  1.70176462e+03   2.55298312e+02   1.84845438e+03   3.66359289e+02
    2.30000000e+01]

Img load: 0.06 seconds
Detect: 0.04 seconds
[[  3.76000000e+02   5.98000000e+02   4.75000000e+02   6.67000000e+02
    9.92194295e-01]
[[  1.69376420e+03   2.51968522e+02   1.84135284e+03   3.63011087e+02
    2.30000000e+01]

Img load: 0.06 seconds
[]
[]
Img load: 0.06 seconds
[]
[]
Img load: 0.06 seconds
[]
[]
Img load: 0.06 seconds
Detect: 0.04 seconds
[[  3.75000000e+02   5.99000000e+02   4.74000000e+02   6.67000000e+02
    9.92482007e-01]
[] 
Img load: 0.07 seconds
[]
[]
Img load: 0.06 seconds
[]
[]
Img load: 0.07 seconds
Detect: 0.04 seconds
[[  3.76000000e+02   5.98000000e+02   4.75000000e+02   6.68000000e+02
    9.92348790e-01]
[]

```

**Comment by abewley** [comment]
To clarify the comment about calling the update() method even with empty detections. This is because the tracker makes a constant velocity assumption and also will delete object if too many frames have passed without seeing them. By default this is set to 1 so if you don't supply detections at least every second frame the objects will be lost. See lines 226-227.

In the case when you are sub-sampling frames and maintaining a fixed frequency you could simply treat the image sequence as a different framerate and you do not need to call it between frames when you are not doing any detection. Although your code appears to already be doing this.

**Comment by TheMikeyR** [comment]
Arhh, I see! Thanks a lot for your time.

**Comment by TheMikeyR** [comment]
For other people who encounter same issue as me:

After some debugging it got to my attention that the `min_hits=3` will remove the tracks if i feed empty detections in,since the min hit only increase when the function is fed detection, so 3 frames with detections in a row will make the counter go to 3, and the updated tracks will be returned. https://github.com/abewley/sort/blob/master/sort.py#L222

Since I'm trying to feed it every frame, and only feed detections every x frame it requires `min_hits=1`, so it is able to give tracks back. To solve it either edit the sort.py default value at https://github.com/abewley/sort/blob/master/sort.py#L176 or when creating the object from your script you can give it a new value as input like `tracker = Sort(min_hits=1)`

Hope this information will help people who encountered the same issue and couldn't figure out a solution.

**Comment by kkyiss** [comment]
Hey @TheMikeyR 
I want to try track with some detect frame skip ,and I have tried your idea above which suggest setting
`tracker = Sort(min_hits=1)`
but still once I feed empty list, the tracker output returns empty

Then I read over the @abewley commented, which said

> By default this is set to 1 so if you don't supply detections at least every second frame the objects will be lost. See lines 226-227.

also with #17 Smmothing detections using tracking , the commented below said

> I changed the following line to https://github.com/abewley/sort/blob/master/sort.py#L222
if((trk.time_since_update < self.max_age+1) and (trk.hit_streak >= self.min_hits or self.frame_count <= self.min_hits)):
>
> and set min_hits=0 and max_age=4

In my opinion, the line "By default this is set to 1" is refer to parameter max_age
and if we increment the value, the tracker can tolerate every q frames with detection information feed

At the end, by adding self.max_age to Line222 and set
`tracker = Sort(max_age=5, min_hits=0)`

I could track with every q frames skip (e.g q = 1 or 2 or 3 or 4 )
if q larger than 5, the max_age has to be larger

not sure I'm doing right, do I miss anything compare to your idea
thanks for any replies

**Comment by TheMikeyR** [comment]
@kkyiss really good point, And I'm sorry I've totally missed to add info about `max_age` parameter, I believe it is due to the reason that I modified it early in my process and forgot that I modified mine when I tried to get frame skip to work. Mine is set to `max_age=10` which makes it able to restore tracks to the old id for a longer timer, since the old id is saved for 10 frames (it can also be dangerous to keep a long history/age, but it seems to work fine with my data).

It looks like you are doing the same steps as I did, so I believe you are doing it right! Thanks for your comment, it will definitely help others who try to achieve the same thing!

**Comment by vivek-singh-rathore** [comment]
I am also trying to skip some frames for detection. But I am having problem in sending empty detections to sort's update function. It gives error in this line when is send an empty list of detections :

trk.update(dets[d,:][0])

IndexError: too many indices for array

**Comment by rishabh700** [comment]
I understand the role of max_age in the code. It helps to keep the tracker_id alive for the set number of frames and hence would reduce the number of new ids assigned to the same object. 

But I am not sure what max_hits is doing? Does it set the minimum number of consecutive detections hits needed to assign the detection a new id if not matched with any other id? Please correct me if I am wrong!
