### ISSUE TITLE
Confidence score hardcoded as 1

### ISSUE THREAD

**Issue by pranamesh** [abewley/sort#23]
The confidence score of predictions after "update" is hardcoded as 1 in Line 282 although it takes the confidence score of original detection in its input in "dets". How can I get the confidence score of bounding box from the tracker output?

Thanks

**Comment by abewley** [comment]
By "confidence score of the bounding box", are you referring to the detection confidence?
If so you can use the assignment matrix to map the detection score to the tracks.
You can also augment the track state space to have the confidence score.
Pull requests are welcome.
