### ISSUE TITLE
MOTA and MOTP

### ISSUE THREAD

**Issue by Phoebe-star** [abewley/sort#25]
how to test the MOTA and MOTP  for sort?
I know the https://motchallenge.net/ 
but I still don't have any idea

**Comment by abewley** [comment]
motchallenge.net provide a devkit which calculates both MOTA and MOTP under the same conditions as for the benchmark.
I also suggest some general reading will help understand these metrics. With a [quick search](http://lmgtfy.com/?q=tracking+MOTA+MOTP) you should find python code, the MOT benchmark paper with the MOTA and MOTP equations and the original paper from Bernardin and Stiefelhagen.
