### ISSUE TITLE
What's meaning of each column of detection txt file? Is there detection score?

### ISSUE THREAD

**Issue by GerrieWell** [abewley/sort#27]
Hi, dear developer. I wonder what's meaning in the column of `gt.txt` OR `det.txt`.
Especially in `det.txt` file, is there any detection score in these elements? I guess the 7th column is the fasterRCNN score, but not sure. 
Would u mind detail each column's meaning and how to genearte it? Thx.

**Comment by MounirB** [comment]
Same as you, I'm looking for the meaning of each column in `det.txt` file. 
- I guess that the 3rd and 4th columns are respectively the x and y coordinates of the top-left point of each pedestrian bounding box. 
- 5th and 6th are the distances from which we can determine the bottom-right point of the same bounding box.
However, me neither I'm not sure about the meaning of the 7th column.

**Comment by abewley** [comment]
You can find the format for the det.txt files here on the [MOT site](https://motchallenge.net/instructions/).
The detector conf in the detections provided with this repo are the predicted class probability for a person.
