### ISSUE TITLE
Steps to track objects on custom dataset

### ISSUE THREAD

**Issue by kristellmarisse** [abewley/sort#3]
Is there any tutorial to implement SORT on custom dataset?

**Comment by abewley** [comment]
Please see the [example](https://github.com/abewley/sort/blob/master/README.md#using-sort-in-your-own-project) at the end of the README for incorporating the tracker in your own project. 

For a more information, you can also look at the [main section](https://github.com/abewley/sort/blob/master/sort.py#L239) of sort.py and adapt it for the particulars of your dataset.
