### ISSUE TITLE
Interpretation of det.txt

### ISSUE THREAD

**Issue by kristellmarisse** [abewley/sort#4]
Every row in det.txt has data like 

1,-1,286.552,154.138,71.337,167.328,0.998331,-1,-1,-1.

So can anyone explain how to interpret this data? I understand the floating point numbers represent bounding box and prediction confidence.

**Comment by abewley** [comment]
Please see the [MOT challenge site](https://motchallenge.net/instructions/) for a description of the data format. These detections are only provided for a demonstration of the tracker and were generated using [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn).
