### ISSUE TITLE
Where's the pretrained model

### ISSUE THREAD

**Issue by Ironeie** [abewley/sort#41]
In fact I don't understand how this project works since I can't find the pretrained model. Will you give the model or the training code?

**Comment by abewley** [comment]
This approach is so simple that you do not need to "pretrain" any model. Everything you need is in the code. 

Note that this code focuses on the task of tracking not detection so you will need detections from your favourite detector. I've supplied some for the MOT benchmark based on FasterRCNN.

If you are after a learnt tracker then please see the [DeepSORT repo](https://github.com/nwojke/deep_sort)

**Comment by Ironeie** [comment]
Thank you so much
