### ISSUE TITLE
Minimum FPS requirement

### ISSUE THREAD

**Issue by Aayushktyagi** [abewley/sort#47]
Can you please suggest minimum fps required for tracking?
(In other words will it work for 1 FPS or 2 FPS because relative change in objects will be large)

Thanks

**Comment by Aayushktyagi** [comment]
After testing tracker , performance of 1 FPS was bad.Although i worked ok 5 FPS and max_age = 1.

**Comment by PBRAOS** [comment]
Is there any tweak to make it work for low FPS ?
