### ISSUE TITLE
The use of List 'history'

### ISSUE THREAD

**Issue by Zhangxianqi** [abewley/sort#51]
Hello, 
Thank you for sharing and I have an issue about the List 'history' defined in the code. 
I see you define a List called  'history' in the line 99 and use it in the line 109, 125 , 126 and realize this List is used to record the previous predict values, but it seems has nothing about the other works such as predict and associate and can be removed. (I removed it, it seems nothing happened)
So why you want record this value?  Could you tell me something about it?

Thanks for your any replies.

**Comment by destinyzs** [comment]
Same question.
