### ISSUE TITLE
Using faster-RCNN for SORT

### ISSUE THREAD

**Issue by harshmunshi** [abewley/sort#6]
I would like to know the basic idea, do we detect and save the bounding box parameters later used for tracking or it can track which the detection(s) are in progress?

Also, is there any script for outputting the labels directly?

**Comment by abewley** [comment]
The box detections from Faster RCNN are saved to file for demonstration purpose. This allows people to run the tracker is without needing to install and integrate Faster RCNN. 

If you want to run the detector on a live image stream and feed the detections directly into the tracker then you will need to:
First follow the [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn) installation instructions  and adapt their demo code to work with your data.
Secondly, feed the detections into the tracker as explained in the [README](https://github.com/abewley/sort#using-sort-in-your-own-project).

**Comment by harshmunshi** [comment]
The data essentially is the bbox information right?

**Comment by abewley** [comment]
That's correct. The files follow the same format as used for the MOT challenge:
https://motchallenge.net/instructions/

**Comment by abewley** [comment]
That's correct. The files follow the same format as used for the MOT
challenge:
https://motchallenge.net/instructions/


Best Regards,
Alex Bewley
