### ISSUE TITLE
Format used in your data

### ISSUE THREAD

**Issue by harshmunshi03** [abewley/sort#7]
Hello Sir,
The data given in your det.txt is of the form:
1,-1,1691.97,381.048,152.23,352.617,0.995616,-1,-1,-1

whereas the mot challenge is of the form:
<frame><id><x><y><h><w><conf><3><d><coordinates>

Why is the id kept as -1?

**Comment by abewley** [comment]
The det.txt file only contained bounding boxes from the detector on a per frame basis. 
These are the inputs to the tracker and it is the tracker's responsibility to give them temporally coherent identities.
