### ISSUE TITLE
what is max_age and min_hits

### ISSUE THREAD

**Issue by M-Younus** [abewley/sort#75]
can you please describe the max_age and min_hits parameters defined in the constructor of Sort class. Thanks

**Comment by LC041336** [comment]
1.max_age:
   (1)"time_since_update" is a flag which represents one of trackers whether predict or not in next frames;
   (2)so "max_age" is the max life period which the unmatched_tracker exists.
2.min_hits:
   (1)"hiit_streak" is a flag which represents one of detection bboxes whether update or not in next frames;
   (2)so "min_hits" is the min accepted number which U detect the result (but I do not track).

**Comment by M-Younus** [comment]
> 1.max_age:
> (1)"time_since_update" is a flag which represents one of trackers whether predict or not in next frames;
> (2)so "max_age" is the max life period which the unmatched_tracker exists.
> 2.min_hits:
> (1)"hiit_streak" is a flag which represents one of detection bboxes whether update or not in next frames;
> (2)so "min_hits" is the min accepted number which U detect the result (but I do not track).

great,Thanks a lot.
