### ISSUE TITLE
(not an issue)is there a way to track live data from a  camera?

### ISSUE THREAD

**Issue by albertyou2** [abewley/sort#8]
hi @abewley 
I run the demo successfully and the result is impressive ! good work!

I'm wandering if sort could be used for live stream data tracking?The data may not be a video file but some frames captured by a camera.and if it could, how to do it?thank you very much!

**Comment by abewley** [comment]
If your live stream includes bounding box detections for the objects you're interested in, then you can just plug them into the tracker with the .update() method as mentioned in the [readme](https://github.com/abewley/sort#using-sort-in-your-own-project).

**Comment by albertyou2** [comment]
@abewley
Sorry for late reply!
I don't have any bounding box in my case ,and all the pedestrians are the objects that i need to track.
Do you mean that any object that I want to tracking must got a bounding box for it if I use sort ?
Thank you!
