### ISSUE TITLE
new improvement about sort

### ISSUE THREAD

**Issue by ujsyehao** [abewley/sort#9]
I combine SSD detection with sort tracking,it performs well,I will give a specific report about the results,Do you have new method or ideas about improving sort algorithm

**Comment by abewley** [comment]
The method itself is a minimal solution to the MOT problem and highlights the importance of good detection. I found that tracking favors detectors with higher precision over recall. 
As mentioned in the paper SORT doesn't handle the issues of occlusion, re-identification or objects lost for a number of frames so there is plenty of work there to be done. 

If you would like to add the SSD detections to SORT then please create a pull request.

**Comment by bigloong** [comment]
@abewley  Can you give me the test sequence detection bbox result to me, Thx.

**Comment by sdsdsd** [comment]
@abewley  I want to do my experiments on Faster RCNN detection , so I need the test sequences result . Can you publish it?

**Comment by ujsyehao** [comment]
@bigloong MOT benchmark provide it .[https://motchallenge.net/results/MOT16/](url)

**Comment by ujsyehao** [comment]
@sdsdsd MOT benchmark provide it .https://motchallenge.net/results/MOT16/

**Comment by ujsyehao** [comment]
@abewley ,Hi, i want to compare sort tracker with other state-of--art tracker,so I can know how to improve it. But in  [https://motchallenge.net/results/2D_MOT_2015/](url), i cannot find your tracker,can you tell me the avg-rank score of your tracker? 
Thank you in advance!

**Comment by abewley** [comment]
Looks like the managers of the benchmark have changed a few things.
You can still find the results on [the results page](https://motchallenge.net/results/2D_MOT_2015/?det=All) if you select "All" for the detections. 
The Avg-rank is currently 31.9. 

Looks like the SORT tracker has created a trend as only 2 out of the top 20 use the provided detections.

**Comment by 3073** [comment]
@usjyehao:   File not found 

https://github.com/abewley/sort/issues/url

**Comment by abewley** [comment]
On 2D MOT 215:
https://motchallenge.net/tracker/SORT

On MOT16:
https://motchallenge.net/tracker/SORTwHPD16

**Comment by 3073** [comment]
Do you mean that this is SSD + SORT?

**Comment by 3073** [comment]
Thank you by the way
